apiVersion: v1
kind: Secret
metadata:
  name: bot-secrets
  namespace: gym-prod
type: Opaque
stringData:
  TOKEN: "7768049946:AAEhgKuUnVb33mlriGZldKFr-Qiv5GInGgk"
  ADMIN_IDS: "851690283"
  WEBHOOK_HOST: "sk1bid.ru"
  WEBHOOK_SECRET: "a5cf1e1b246bc1aff86f577b252128c679b51f83d680ccb03dd950177ec1d3a3"
  WEBHOOK_PATH: "/tg/webhook"
  POSTGRES_USER: "prod_user"
  POSTGRES_PASSWORD: "22856719d8Sk1bid"
  POSTGRES_DB: "gymassistant"
  DB_URL: "postgresql+asyncpg://prod_user:22856719d8Sk1bid@postgres:5432/gymassistant"
  PORT: "8080"
  NEIRO_API_URL: "http://press-api.gym-prod.svc.cluster.local:8000/predict"
